GET http://localhost:8010/peliculas/2

Content-Type: application/json

###

GET http://localhost:8010/peliculas/1003
Content-Type: application/json

###

POST http://localhost:8010/peliculas
Content-Type: application/json

{
    "title": "PRUEBA",
    "description": "A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies",
    "id": 0,
    "language": 2,
    "rental_duration": 6,
    "rental_rate": 0.99,
    "rep_cost": 20.99,
    "last_update": "2006-02-15T04:03:42.000+00:00"
  }

###

PUT    http://localhost:8010/peliculas/1003
Content-Type: application/json

{
    "title": "NO ES UNA PRUEBA",
    "description": "A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies",
    "id": 1003,
    "language": 6,
    "rental_duration": 6,
    "rental_rate": 0.99,
    "rep_cost": 20.99,
    "last_update": "2006-02-15T04:03:42.000+00:00"
  }

### 

DELETE http://localhost:8010/peliculas/1003


### 

GET http://localhost:8010/idioma/2

Content-Type: application/json

### 

GET http://localhost:8010/idioma/

Content-Type: application/json

###

POST http://localhost:8010/idioma
Content-Type: application/json

{
    "languageId": 0,
    "name": "Español"
  }


###

PUT http://localhost:8010/idioma/7
Content-Type: application/json

{
    "languageId": 7,
    "name": "Ruso"
  }


  ### 

DELETE http://localhost:8010/idioma/7